spring:
  application:
    name: ParcelDelivery

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_app_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

pricing:
  base-fee: 2.00
  rate-per-km: 1
  rate-per-kg: 0.50

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

admin:
  seed:
    email: ${ADMIN_SEED_EMAIL:admin@hermes.local}
    password: ${ADMIN_SEED_PASSWORD:}

#azure:
#  cosmos:
#    uri: https://localhost:8081
#    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
#    database: <your-database-name>
#    populate-query-metrics: false
