spring:
  application:
    name: HermesProfile
  datasource:
    url: jdbc:postgresql://localhost:5432/hermes_profile_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8082}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}

nominatim:
  user-agent: ${NOMINATIM_USER_AGENT:HermesProfileService/1.0}

management:
  endpoints:
    web:
      exposure:
        include: health
