spring:
  application:
    name: HermesDelivery

  datasource:
    url: jdbc:postgresql://localhost:5432/hermes_delivery_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8084}

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health

pricing:
  base-fee: 2.00
  rate-per-km: 1
  rate-per-kg: 0.50

nominatim:
  user-agent: ${NOMINATIM_USER_AGENT}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:dummy-test-key-not-real}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://user-service:8081}

profile-service:
  base-url: ${PROFILE_SERVICE_BASE_URL:http://profile-service:8082}

wallet-service:
  base-url: ${WALLET_SERVICE_BASE_URL:http://wallet-service:8083}
